server:
    port: 9090

filestore:
    baseUrl: ./store

spring:
    datasource:
        url: jdbc:h2:mem:testdb  
        driverClassName: org.h2.Driver  
        username: sa  
        password:
    h2:
        console:
            enabled: true
