server:
    port: 9898
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka

spring:
    application:
        name: core-service
    datasource:
        url: jdbc:postgresql://127.0.01:5432/core
        username: core_admin
        password: admin123
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
